# Generated by Django 4.0.4 on 2022-05-30 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_user_created_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
