# Generated by Django 4.0.4 on 2022-05-30 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_user_created_alter_user_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
