# Generated by Django 4.0.4 on 2022-06-13 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_user_is_staff_readitem_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='readitem',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
