# Generated by Django 4.0.4 on 2022-06-26 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_goal_created_alter_readitem_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('thumbnail_link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='goal',
            name='website_count',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='website_goal',
        ),
        migrations.DeleteModel(
            name='ReadItem',
        ),
    ]
